name: secret-scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gitleaks
        uses: https://gitea.stump.rocks/stumpcloud/gitleaks-action@v1
        with:
          gitea-token: ${{ github.token }}
          publish: "false"
